name: Sample CI Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: setup-scala
        uses: olafurpg/setup-scala@v10
      - name: Unit test
        run: sbt test
